name: Run tests and release

on:
  push:
    tags:
      - "*"
  workflow_dispatch:
  workflow_call:

jobs:
  build-python-wheel:
    name: "🐍 Python Wheel"
    uses: ./.github/workflows/wheel.yml
    secrets: inherit

  release-pypi:
    name: "🐍 Release on PyPI"
    runs-on: ubuntu-latest
    needs: [build-python-wheel]
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    environment:
      name: pypi
      url: https://pypi.org/p/pgserviceparser
    permissions:
      id-token: write

    steps:
      - name: Retrieve artifact from Python build
        uses: actions/download-artifact@v4
        with:
          name: python_wheel
          path: dist/

      - name: upload release asset
        run: gh release upload ${{ github.ref_name }} "dist/*.tar.gz"

      - name: Deploy to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1

        with:
          user: __token__
          password: ${{ secrets.PYPI_API_TOKEN }}
